spring:

  datasource:
    url: jdbc:h2:mem://localhost:3306/
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  session:
    store-type: jdbc

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 773822756573-sq2fpu1iv3pc6j8q6fuchgt50f8jrtl0.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

          naver:
            client-id: BJXK37WtqADgwz_QtJ23
            client-secret: G1vGgttnqK
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver

      provider:
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: response