spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/play-ground
    username:
    password:

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

