spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/play-ground
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

h2-datasource:
  url: jdbc:h2:mem:test
  username: sa
  password:
  driver-class-name: org.h2.Driver
