spring:

  datasource:
    url: 디비서버정보
    username: 사용자아이디
    password: 비밀번호

  h2:
    console:
      enabled: true

  redis:
    host: 레디스서버정보
    port: 6379

  kafka:
    consumer:
      bootstrap-servers: 카프카서버정보
      group-id: foo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  session:
    store-type: jdbc

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 클라이언트아이디
            client-secret: 클라이언트시크릿
            scope:
              - profile
              - email

          naver:
            client-id: 클라이언트아이디
            client-secret: 클라이언트시크릿
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            #            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver

          kakao:
            client-id: 클라이언트아이디
            client-secret: 클라이언트시크릿
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            #            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope:
              - profile_nickname
              - account_email
              - profile_image
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

cloud:
  aws:
    credentials:
      accessKey: 접근키
      secretKey: 시크릿키
    s3:
      bucket: 버킷이름

    region:
      static: 리전이름

logging:
  level:
    root: debug
